Controllers/CreateController.cs
using dnd123.Data;
using dnd123.Models.Character;
using dnd123.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dnd123.Controllers
{
    public class CreateController : Controller
    {
        private CharacterDbContext context;

        public CreateController(CharacterDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Index()
        {
            List<Character> Characters = context.Characters.ToList();

            return View(Characters);
        }

        public IActionResult Add()
        {
            AddCharacterViewModel addCharacterViewModel = new AddCharacterViewModel();

            return View(addCharacterViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddCharacterViewModel addCharacterViewModel, string[] selectedSkills)
        {
            if (ModelState.IsValid)
            {
                Character newCharacter = new Character
                {
                    Name = addCharacterViewModel.Name,
                    Bio = addCharacterViewModel.Bio,
                    CharacterClass = addCharacterViewModel.CharacterClass,
                    Race = addCharacterViewModel.Race,
                };

                for (int i = 0; i < selectedSkills.Length; i++)
                {
                    CharacterAbility ability = new CharacterAbility
                    {
                        CharacterId = newCharacter.Id,
                        Character = newCharacter,
                        AbilityId = Int32.Parse(selectedSkills[i]),
                    };
                    context.CharacterAbility.Add(ability);
                }

                context.Characters.Add(newCharacter);
                context.SaveChanges();

                return Redirect("/Create");
            }

            return View(addCharacterViewModel);
        }

        public IActionResult Delete()
        {
            ViewBag.characters = context.Characters.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] characterIds)
        {
            foreach (int characterId in characterIds)
            {
                Character theCharacter = context.Characters.Find(characterId);
                context.Characters.Remove(theCharacter);
            }
            context.SaveChanges();

            return Redirect("/Create");
        }
    }
} 

Controllers/LearnController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dnd123.Controllers
{
    public class LearnController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace dnd123.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dnd123</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css"/>
</head>
<body>

    <header>
        <div>
            <ul>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Create" asp-action="Index">Create</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Learn" asp-action="Index">Learn</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                </li>
                @if (signInManager.IsSignedIn(User))
                {
                    <li>
                        <form method="post" asp-action="logout" asp-controller="account">
                            <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">Logout @User.Identity.Name</button>
                        </form>
                    </li>
                }
                else
                {
                    <li>
                        <a asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                }

            </ul>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - dnd123 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/11f0eab996.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>